### ISSUE TITLE
Choose a licence

### ISSUE THREAD

**Issue by trickytank** [bahlolab/linkdatagen-manual#1]
I want to add a Creative Commons licence to this manual. 

I'm thinking to choose an [Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)](https://creativecommons.org/licenses/by-nc-nd/4.0/). In summary, this is:

Users are free to copy and redistribute the material in any medium or format, under the following terms:
- Attribution — You must give [appropriate credit](https://creativecommons.org/licenses/by-nc-nd/4.0/#), provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by-nc-nd/4.0/#). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- NonCommercial — You may not use the material for [commercial purposes](https://creativecommons.org/licenses/by-nc-nd/4.0/#). 
- NoDerivatives — If you [remix, transform, or build upon](https://creativecommons.org/licenses/by-nc-nd/4.0/#) the material, you may not distribute the modified material.
- No additional restrictions — You may not apply legal terms or [technological measures](https://creativecommons.org/licenses/by-nc-nd/4.0/#) that legally restrict others from doing anything the license permits.

Do we use the [Attribution-NoDerivatives 4.0 International](http://creativecommons.org/licenses/by-nd/4.0/) instead that does not have the commercial restriction? I'm thinking not, as we may not want to close off the opportunity for royalties for commercial use of LINKDATAGEN.

**Comment by mbahlo** [comment]
Sounds fine to be Rick!

**Comment by trickytank** [comment]
The [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) has been added.
